export const merchant_store = pgTable('merchant_stores', {
  id: bigint('id', { mode: 'number' }).primaryKey(),
  store_id: text('store_id').notNull(),
  parent_id: bigint('parent_id', { mode: 'number' }),
  store_name: text('store_name').notNull(),
  cuisine_type: text('cuisine_type').array().notNull(),
  store_email: text('store_email'),
  store_phones: text('store_phones').array(),
  store_description: text('store_description'),
  store_banner_url: text('store_banner_url'),
  logo_url: text('logo_url'),
  ads_images: text('ads_images').array(),
  full_address: text('full_address').notNull(),
  city: text('city').notNull(),
  state: text('state').notNull(),
  landmark: text('landmark'),
  postal_code: text('postal_code').notNull(),
  latitude: numeric('latitude', { precision: 9, scale: 6 }),
  longitude: numeric('longitude', { precision: 9, scale: 6 }),
  gst_number: text('gst_number'),
  gst_image_url: text('gst_image_url'),
  pan_number: text('pan_number').notNull(),
  pan_image_url: text('pan_image_url').notNull(),
  aadhaar_number: text('aadhaar_number').notNull(),
  aadhaar_image_url: text('aadhaar_image_url').notNull(),
  fssai_number: text('fssai_number'),
  fssai_image_url: text('fssai_image_url'),
  bank_account_holder: text('bank_account_holder').notNull(),
  bank_account_number: text('bank_account_number').notNull(),
  bank_ifsc: text('bank_ifsc').notNull(),
  bank_name: text('bank_name').notNull(),
  opening_time: time('opening_time').notNull(),
  closing_time: time('closing_time').notNull(),
  closed_days: text('closed_days').array(),
  avg_delivery_time_minutes: integer('avg_delivery_time_minutes'),
  min_order_amount: numeric('min_order_amount', { precision: 10, scale: 2 }),
  has_area_manager: boolean('has_area_manager').default(false),
  am_name: text('am_name'),
  am_mobile: text('am_mobile'),
  am_email: text('am_email'),
  approval_status: text('approval_status').default('SUBMITTED'),
  approval_reason: text('approval_reason'),
  approved_by: text('approved_by'),
  approved_by_email: text('approved_by_email'),
  approved_at: timestamp('approved_at', { withTimezone: true }),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  is_active: boolean('is_active').default(true),
  deleted_at: timestamp('deleted_at', { withTimezone: true }),
  current_step: integer('current_step').default(1),
});
export const item_addons = pgTable('item_addons', {
  id: serial('id').primaryKey(),
  customization_id: varchar('customization_id', { length: 64 }),
  addon_name: varchar('addon_name', { length: 255 }),
  addon_price: numeric('addon_price'),
});
export const item_customizations = pgTable('item_customizations', {
  id: serial('id').primaryKey(),
  menu_item_id: varchar('menu_item_id', { length: 64 }),
  title: varchar('title', { length: 255 }),
  required: boolean('required'),
  max_selection: varchar('max_selection', { length: 16 }),
});
import { pgTable, varchar, boolean, numeric, serial, bigint, text, time, integer, timestamp } from 'drizzle-orm/pg-core';

export const menu_items = pgTable('menu_items', {
  id: serial('id').primaryKey(),
  item_id: varchar('item_id', { length: 64 }),
  store_id: varchar('store_id', { length: 64 }),
  item_name: varchar('item_name', { length: 255 }),
  description: varchar('description', { length: 1024 }),
  category_type: varchar('category_type', { length: 255 }),
  food_category_item: varchar('food_category_item', { length: 255 }),
  actual_price: numeric('actual_price'),
  offer_price: numeric('offer_price'),
  in_stock: boolean('in_stock'),
  has_customization: boolean('has_customization'),
  has_addons: boolean('has_addons'),
  image_url: varchar('image_url', { length: 1024 }),
  is_active: boolean('is_active'),
});
