import { z } from 'zod';

export const storeSchema = z.object({
  parent_id: z.number().int().positive(),
  store_name: z.string().min(2, 'Store name is required'),
  cuisine_type: z.array(z.string()).min(1, 'At least one cuisine type required'),
  store_description: z.string().min(5, 'Description required'),
  store_email: z.string().email('Invalid email'),
  store_phones: z.array(z.string()).min(1, 'At least one phone required'),
  store_banner_url: z.string().url('Banner image required'),
  ads_images: z.array(z.string().url()).max(5),
  full_address: z.string().min(5),
  city: z.string().min(2),
  state: z.string().min(2),
  landmark: z.string().optional(),
  postal_code: z.string().min(4),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
  pan_number: z.string().min(5),
  pan_image_url: z.string().url('PAN image required'),
  aadhar_number: z.string().min(5),
  aadhar_image_url: z.string().url('Aadhar image required'),
  gst_number: z.string().optional(),
  gst_image_url: z.string().url().optional(),
  fssai_number: z.string().optional(),
  fssai_image_url: z.string().url().optional(),
  bank_account_holder: z.string().min(2),
  bank_account_number: z.string().min(5),
  bank_ifsc: z.string().min(5),
  bank_name: z.string().min(2),
  opening_time: z.string().min(1),
  closing_time: z.string().min(1),
  closed_days: z.array(z.string()),
  avg_delivery_time_minutes: z.number().int().optional(),
  min_order_amount: z.number().optional(),
  has_area_manager: z.boolean(),
  am_name: z.string().optional(),
  am_mobile: z.string().optional(),
  am_email: z.string().email().optional(),
});

export type StoreInput = z.infer<typeof storeSchema>;
