-- ============================================================================
-- UNIFIED TICKET SYSTEM
-- ============================================================================
-- This migration creates a comprehensive, unified ticket system that supports:
-- - All ticket types: Order-related and Non-order-related
-- - All sources: Customer, Rider, Merchant, System (Auto), Email
-- - All services: Food, Parcel, Ride
-- - Fixed ticket titles for consistency
-- ============================================================================

-- ============================================================================
-- ENUMS
-- ============================================================================

-- Ticket Source (who/what created the ticket)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unified_ticket_source') THEN
    CREATE TYPE unified_ticket_source AS ENUM (
      'CUSTOMER',      -- Customer raised via app
      'RIDER',         -- Rider raised via app
      'MERCHANT',      -- Merchant raised via app
      'SYSTEM',        -- Auto-generated by system
      'EMAIL',         -- Created from email
      'AGENT',         -- Created by support agent
      'WHATSAPP',      -- Created from WhatsApp
      'CALL'           -- Created from phone call
    );
  END IF;
END $$;

-- Ticket Type (order-related or not)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unified_ticket_type') THEN
    CREATE TYPE unified_ticket_type AS ENUM (
      'ORDER_RELATED',     -- Ticket is related to a specific order
      'NON_ORDER_RELATED'  -- Ticket is not related to any order (general support)
    );
  END IF;
END $$;

-- Service Type (which service the ticket is about)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unified_ticket_service_type') THEN
    CREATE TYPE unified_ticket_service_type AS ENUM (
      'FOOD',      -- Food delivery service
      'PARCEL',    -- Parcel delivery service
      'RIDE',      -- Ride booking service
      'GENERAL'    -- General support (not service-specific)
    );
  END IF;
END $$;

-- Ticket Title (Fixed titles for consistency)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unified_ticket_title') THEN
    CREATE TYPE unified_ticket_title AS ENUM (
  -- ORDER-RELATED TITLES
  'ORDER_DELAYED',
  'ORDER_NOT_RECEIVED',
  'WRONG_ITEM_DELIVERED',
  'ITEM_MISSING',
  'ORDER_CANCELLED_WRONG',
  'PAYMENT_ISSUE',
  'REFUND_NOT_PROCESSED',
  'ORDER_DAMAGED',
  'ORDER_QUALITY_ISSUE',
  'RIDER_NOT_ARRIVED',
  'RIDER_BEHAVIOUR_ISSUE',
  'MERCHANT_NOT_PREPARING',
  'DELIVERY_ADDRESS_WRONG',
  'ORDER_NOT_ASSIGNED',
  'ORDER_REASSIGNMENT_NEEDED',
  
  -- NON-ORDER-RELATED TITLES (CUSTOMER)
  'ACCOUNT_ISSUE',
  'PAYMENT_METHOD_ISSUE',
  'WALLET_ISSUE',
  'COUPON_NOT_APPLYING',
  'APP_TECHNICAL_ISSUE',
  'PROFILE_UPDATE_ISSUE',
  'ADDRESS_MANAGEMENT_ISSUE',
  'NOTIFICATION_NOT_RECEIVING',
  
  -- NON-ORDER-RELATED TITLES (RIDER)
  'EARNINGS_NOT_CREDITED',
  'WALLET_WITHDRAWAL_ISSUE',
  'APP_CRASH_OR_BUG',
  'LOCATION_TRACKING_ISSUE',
  'RIDER_ORDER_NOT_RECEIVING',
  'ONBOARDING_ISSUE',
  'DOCUMENT_VERIFICATION_ISSUE',
  'DUTY_LOG_ISSUE',
  'RATING_DISPUTE',
  
  -- NON-ORDER-RELATED TITLES (MERCHANT)
  'PAYOUT_DELAYED',
  'PAYOUT_NOT_RECEIVED',
  'SETTLEMENT_DISPUTE',
  'COMMISSION_DISPUTE',
  'MENU_UPDATE_ISSUE',
  'STORE_STATUS_ISSUE',
  'MERCHANT_ORDER_NOT_RECEIVING',
  'MERCHANT_APP_TECHNICAL_ISSUE',
  'VERIFICATION_ISSUE',
  
  -- GENERAL TITLES
  'OTHER',
  'FEEDBACK',
  'COMPLAINT',
  'SUGGESTION'
    );
  END IF;
END $$;

-- Ticket Status (lifecycle)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unified_ticket_status') THEN
    CREATE TYPE unified_ticket_status AS ENUM (
      'OPEN',                    -- Just created
      'IN_PROGRESS',            -- Assigned and being worked on
      'WAITING_FOR_USER',       -- Waiting for user response
      'WAITING_FOR_MERCHANT',   -- Waiting for merchant response
      'WAITING_FOR_RIDER',      -- Waiting for rider response
      'RESOLVED',               -- Resolved but not closed
      'CLOSED',                 -- Closed by agent/user
      'ESCALATED',              -- Escalated to higher level
      'REOPENED',               -- Reopened after closure
      'CANCELLED'               -- Cancelled
    );
  END IF;
END $$;

-- Ticket Priority
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unified_ticket_priority') THEN
    CREATE TYPE unified_ticket_priority AS ENUM (
      'LOW',
      'MEDIUM',
      'HIGH',
      'URGENT',
      'CRITICAL'
    );
  END IF;
END $$;

-- Ticket Category (for better organization)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'unified_ticket_category') THEN
    CREATE TYPE unified_ticket_category AS ENUM (
      'ORDER',           -- Order-related issues
      'PAYMENT',         -- Payment issues
      'DELIVERY',        -- Delivery issues
      'REFUND',          -- Refund requests
      'ACCOUNT',         -- Account issues
      'TECHNICAL',       -- Technical/app issues
      'EARNINGS',        -- Earnings/payout issues (rider/merchant)
      'VERIFICATION',    -- KYC/verification issues
      'COMPLAINT',       -- General complaints
      'FEEDBACK',        -- Feedback/suggestions
      'OTHER'            -- Other issues
    );
  END IF;
END $$;

-- ============================================================================
-- UNIFIED TICKETS TABLE (Main Table)
-- ============================================================================

CREATE TABLE IF NOT EXISTS unified_tickets (
  id BIGSERIAL PRIMARY KEY,
  ticket_id TEXT NOT NULL UNIQUE, -- Human-readable ticket ID (e.g., TKT-2024-001234)
  
  -- Ticket Classification
  ticket_type unified_ticket_type NOT NULL,
  ticket_source unified_ticket_source NOT NULL,
  service_type unified_ticket_service_type NOT NULL,
  ticket_title unified_ticket_title NOT NULL,
  ticket_category unified_ticket_category NOT NULL,
  
  -- Related Entities (can be NULL for non-order-related tickets)
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  rider_id INTEGER REFERENCES riders(id) ON DELETE SET NULL,
  merchant_store_id BIGINT REFERENCES merchant_stores(id) ON DELETE SET NULL,
  merchant_parent_id BIGINT REFERENCES merchant_parents(id) ON DELETE SET NULL,
  
  -- Raised By Information
  raised_by_type unified_ticket_source NOT NULL, -- Who raised it
  raised_by_id BIGINT, -- ID of the person who raised (customer_id, rider_id, merchant_id, etc.)
  raised_by_name TEXT, -- Name snapshot
  raised_by_mobile TEXT, -- Mobile snapshot
  raised_by_email TEXT, -- Email snapshot
  
  -- Ticket Details
  subject TEXT NOT NULL, -- Custom subject (can override title)
  description TEXT NOT NULL, -- Detailed description
  attachments TEXT[], -- URLs to attached files/images
  
  -- Priority & Status
  priority unified_ticket_priority NOT NULL DEFAULT 'MEDIUM',
  status unified_ticket_status NOT NULL DEFAULT 'OPEN',
  
  -- Assignment
  assigned_to_agent_id INTEGER REFERENCES system_users(id) ON DELETE SET NULL,
  assigned_to_agent_name TEXT,
  assigned_at TIMESTAMP WITH TIME ZONE,
  auto_assigned BOOLEAN DEFAULT FALSE, -- Whether auto-assigned by system
  
  -- Resolution
  resolution TEXT,
  resolution_time_minutes INTEGER, -- Time taken to resolve
  resolved_at TIMESTAMP WITH TIME ZONE,
  resolved_by INTEGER REFERENCES system_users(id) ON DELETE SET NULL,
  resolved_by_name TEXT,
  
  -- Escalation
  escalated BOOLEAN DEFAULT FALSE,
  escalated_at TIMESTAMP WITH TIME ZONE,
  escalated_to INTEGER REFERENCES system_users(id) ON DELETE SET NULL,
  escalated_reason TEXT,
  escalation_level INTEGER DEFAULT 0, -- 0 = normal, 1 = first escalation, 2 = second, etc.
  
  -- Response Tracking
  first_response_at TIMESTAMP WITH TIME ZONE,
  first_response_time_minutes INTEGER, -- Time to first response
  last_response_at TIMESTAMP WITH TIME ZONE,
  last_response_by_type unified_ticket_source, -- Who responded last
  last_response_by_id BIGINT,
  
  -- Follow-up
  follow_up_required BOOLEAN DEFAULT FALSE,
  follow_up_date TIMESTAMP WITH TIME ZONE,
  follow_up_notes TEXT,
  
  -- Satisfaction
  satisfaction_rating SMALLINT CHECK (satisfaction_rating >= 1 AND satisfaction_rating <= 5),
  satisfaction_feedback TEXT,
  satisfaction_collected_at TIMESTAMP WITH TIME ZONE,
  
  -- Parent/Child Relationships (for ticket linking)
  parent_ticket_id BIGINT REFERENCES unified_tickets(id) ON DELETE SET NULL,
  related_ticket_ids BIGINT[], -- Array of related ticket IDs
  
  -- Tags for filtering/searching
  tags TEXT[],
  
  -- Email Integration (if created from email)
  email_message_id TEXT, -- Original email message ID
  email_thread_id TEXT, -- Email thread ID for grouping
  email_from_address TEXT,
  email_subject TEXT,
  
  -- Auto-Generated Ticket Metadata
  auto_generated BOOLEAN DEFAULT FALSE,
  auto_generation_rule TEXT, -- Rule that triggered auto-generation
  auto_generation_metadata JSONB DEFAULT '{}',
  
  -- Metadata
  metadata JSONB DEFAULT '{}', -- Additional flexible data
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  closed_at TIMESTAMP WITH TIME ZONE,
  
  -- Constraints
  CONSTRAINT unified_tickets_order_check CHECK (
    (ticket_type = 'ORDER_RELATED' AND order_id IS NOT NULL) OR
    (ticket_type = 'NON_ORDER_RELATED' AND order_id IS NULL)
  ),
  CONSTRAINT unified_tickets_raised_by_check CHECK (
    (raised_by_type = 'CUSTOMER' AND raised_by_id IS NOT NULL AND customer_id IS NOT NULL) OR
    (raised_by_type = 'RIDER' AND raised_by_id IS NOT NULL AND rider_id IS NOT NULL) OR
    (raised_by_type = 'MERCHANT' AND raised_by_id IS NOT NULL AND (merchant_store_id IS NOT NULL OR merchant_parent_id IS NOT NULL)) OR
    (raised_by_type IN ('SYSTEM', 'EMAIL', 'AGENT', 'WHATSAPP', 'CALL'))
  )
);

-- Indexes for Performance
CREATE INDEX IF NOT EXISTS unified_tickets_ticket_id_idx ON unified_tickets(ticket_id);
CREATE INDEX IF NOT EXISTS unified_tickets_order_id_idx ON unified_tickets(order_id) WHERE order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS unified_tickets_customer_id_idx ON unified_tickets(customer_id) WHERE customer_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS unified_tickets_rider_id_idx ON unified_tickets(rider_id) WHERE rider_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS unified_tickets_merchant_store_id_idx ON unified_tickets(merchant_store_id) WHERE merchant_store_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS unified_tickets_merchant_parent_id_idx ON unified_tickets(merchant_parent_id) WHERE merchant_parent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS unified_tickets_ticket_type_idx ON unified_tickets(ticket_type);
CREATE INDEX IF NOT EXISTS unified_tickets_ticket_source_idx ON unified_tickets(ticket_source);
CREATE INDEX IF NOT EXISTS unified_tickets_service_type_idx ON unified_tickets(service_type);
CREATE INDEX IF NOT EXISTS unified_tickets_ticket_title_idx ON unified_tickets(ticket_title);
CREATE INDEX IF NOT EXISTS unified_tickets_ticket_category_idx ON unified_tickets(ticket_category);
CREATE INDEX IF NOT EXISTS unified_tickets_status_idx ON unified_tickets(status);
CREATE INDEX IF NOT EXISTS unified_tickets_priority_idx ON unified_tickets(priority);
CREATE INDEX IF NOT EXISTS unified_tickets_assigned_to_agent_id_idx ON unified_tickets(assigned_to_agent_id) WHERE assigned_to_agent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS unified_tickets_raised_by_type_idx ON unified_tickets(raised_by_type);
CREATE INDEX IF NOT EXISTS unified_tickets_raised_by_id_idx ON unified_tickets(raised_by_id) WHERE raised_by_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS unified_tickets_parent_ticket_id_idx ON unified_tickets(parent_ticket_id) WHERE parent_ticket_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS unified_tickets_created_at_idx ON unified_tickets(created_at);
CREATE INDEX IF NOT EXISTS unified_tickets_updated_at_idx ON unified_tickets(updated_at);
CREATE INDEX IF NOT EXISTS unified_tickets_tags_idx ON unified_tickets USING GIN(tags);
CREATE INDEX IF NOT EXISTS unified_tickets_metadata_idx ON unified_tickets USING GIN(metadata);
CREATE INDEX IF NOT EXISTS unified_tickets_email_thread_id_idx ON unified_tickets(email_thread_id) WHERE email_thread_id IS NOT NULL;

-- Composite Indexes for Common Queries
CREATE INDEX IF NOT EXISTS unified_tickets_status_priority_idx ON unified_tickets(status, priority);
CREATE INDEX IF NOT EXISTS unified_tickets_service_type_status_idx ON unified_tickets(service_type, status);
CREATE INDEX IF NOT EXISTS unified_tickets_ticket_type_service_type_idx ON unified_tickets(ticket_type, service_type);
CREATE INDEX IF NOT EXISTS unified_tickets_assigned_agent_status_idx ON unified_tickets(assigned_to_agent_id, status) WHERE assigned_to_agent_id IS NOT NULL;

-- ============================================================================
-- TICKET MESSAGES (Conversation Thread)
-- ============================================================================

CREATE TABLE IF NOT EXISTS unified_ticket_messages (
  id BIGSERIAL PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES unified_tickets(id) ON DELETE CASCADE,
  
  -- Message Details
  message_text TEXT NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'TEXT', -- 'TEXT', 'IMAGE', 'FILE', 'SYSTEM', 'EMAIL'
  
  -- Sender Information
  sender_type unified_ticket_source NOT NULL,
  sender_id BIGINT, -- ID of sender (customer_id, rider_id, merchant_id, agent_id)
  sender_name TEXT,
  sender_email TEXT,
  sender_mobile TEXT,
  
  -- Attachments
  attachments TEXT[], -- URLs to files/images
  
  -- Internal Notes (only visible to agents)
  is_internal_note BOOLEAN DEFAULT FALSE,
  internal_note_for_agent_id INTEGER REFERENCES system_users(id) ON DELETE SET NULL,
  
  -- Read Status
  is_read BOOLEAN DEFAULT FALSE,
  read_at TIMESTAMP WITH TIME ZONE,
  read_by INTEGER REFERENCES system_users(id) ON DELETE SET NULL,
  
  -- Email Integration (if message came from email)
  email_message_id TEXT,
  email_in_reply_to TEXT,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS unified_ticket_messages_ticket_id_idx ON unified_ticket_messages(ticket_id);
CREATE INDEX IF NOT EXISTS unified_ticket_messages_sender_type_idx ON unified_ticket_messages(sender_type);
CREATE INDEX IF NOT EXISTS unified_ticket_messages_sender_id_idx ON unified_ticket_messages(sender_id) WHERE sender_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS unified_ticket_messages_created_at_idx ON unified_ticket_messages(created_at);
CREATE INDEX IF NOT EXISTS unified_ticket_messages_is_internal_note_idx ON unified_ticket_messages(is_internal_note);

-- ============================================================================
-- TICKET ACTIVITY LOG (Audit Trail)
-- ============================================================================

CREATE TABLE IF NOT EXISTS unified_ticket_activities (
  id BIGSERIAL PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES unified_tickets(id) ON DELETE CASCADE,
  
  -- Activity Details
  activity_type TEXT NOT NULL, -- 'CREATED', 'ASSIGNED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'ESCALATED', 'RESOLVED', 'CLOSED', 'REOPENED', 'MESSAGE_ADDED', etc.
  activity_description TEXT NOT NULL,
  
  -- Actor
  actor_type unified_ticket_source NOT NULL,
  actor_id BIGINT,
  actor_name TEXT,
  
  -- Changes (JSONB for flexible change tracking)
  old_value JSONB,
  new_value JSONB,
  
  -- Timestamp
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS unified_ticket_activities_ticket_id_idx ON unified_ticket_activities(ticket_id);
CREATE INDEX IF NOT EXISTS unified_ticket_activities_activity_type_idx ON unified_ticket_activities(activity_type);
CREATE INDEX IF NOT EXISTS unified_ticket_activities_actor_type_idx ON unified_ticket_activities(actor_type);
CREATE INDEX IF NOT EXISTS unified_ticket_activities_created_at_idx ON unified_ticket_activities(created_at);

-- ============================================================================
-- TICKET TITLE CONFIGURATION (Reference Table for Fixed Titles)
-- ============================================================================

CREATE TABLE IF NOT EXISTS ticket_title_config (
  id BIGSERIAL PRIMARY KEY,
  ticket_title unified_ticket_title NOT NULL UNIQUE,
  
  -- Title Details
  display_name TEXT NOT NULL, -- Human-readable name
  description TEXT, -- Description of when to use this title
  
  -- Applicability
  applicable_to_ticket_type unified_ticket_type[], -- Which ticket types can use this
  applicable_to_service_type unified_ticket_service_type[], -- Which services can use this
  applicable_to_source unified_ticket_source[], -- Which sources can use this
  
  -- Default Settings
  default_priority unified_ticket_priority,
  default_category unified_ticket_category,
  default_auto_assign BOOLEAN DEFAULT FALSE,
  default_auto_assign_to_agent_id INTEGER REFERENCES system_users(id) ON DELETE SET NULL,
  
  -- Status
  is_active BOOLEAN DEFAULT TRUE,
  display_order INTEGER DEFAULT 0, -- For UI ordering
  
  -- Metadata
  metadata JSONB DEFAULT '{}',
  
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS ticket_title_config_ticket_title_idx ON ticket_title_config(ticket_title);
CREATE INDEX IF NOT EXISTS ticket_title_config_is_active_idx ON ticket_title_config(is_active);
CREATE INDEX IF NOT EXISTS ticket_title_config_display_order_idx ON ticket_title_config(display_order);

-- ============================================================================
-- AUTO-GENERATION RULES (For System-Generated Tickets)
-- ============================================================================

CREATE TABLE IF NOT EXISTS ticket_auto_generation_rules (
  id BIGSERIAL PRIMARY KEY,
  rule_name TEXT NOT NULL UNIQUE,
  rule_description TEXT,
  
  -- Trigger Conditions
  trigger_event TEXT NOT NULL, -- 'ORDER_DELAYED', 'PAYMENT_FAILED', 'RIDER_NOT_ASSIGNED', etc.
  trigger_conditions JSONB NOT NULL DEFAULT '{}', -- Conditions that must be met
  
  -- Ticket Generation Settings
  ticket_title unified_ticket_title NOT NULL,
  ticket_type unified_ticket_type NOT NULL,
  ticket_category unified_ticket_category NOT NULL,
  service_type unified_ticket_service_type NOT NULL,
  priority unified_ticket_priority NOT NULL DEFAULT 'MEDIUM',
  
  -- Auto-Assignment
  auto_assign BOOLEAN DEFAULT FALSE,
  auto_assign_to_agent_id INTEGER REFERENCES system_users(id) ON DELETE SET NULL,
  auto_assign_to_department TEXT, -- Department name for routing
  
  -- Status
  is_active BOOLEAN DEFAULT TRUE,
  is_enabled BOOLEAN DEFAULT TRUE,
  
  -- Metadata
  metadata JSONB DEFAULT '{}',
  
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS ticket_auto_generation_rules_trigger_event_idx ON ticket_auto_generation_rules(trigger_event);
CREATE INDEX IF NOT EXISTS ticket_auto_generation_rules_is_active_idx ON ticket_auto_generation_rules(is_active);
CREATE INDEX IF NOT EXISTS ticket_auto_generation_rules_is_enabled_idx ON ticket_auto_generation_rules(is_enabled);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Update updated_at timestamp
DROP TRIGGER IF EXISTS unified_tickets_updated_at_trigger ON unified_tickets;
CREATE TRIGGER unified_tickets_updated_at_trigger
  BEFORE UPDATE ON unified_tickets
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS unified_ticket_messages_updated_at_trigger ON unified_ticket_messages;
CREATE TRIGGER unified_ticket_messages_updated_at_trigger
  BEFORE UPDATE ON unified_ticket_messages
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS ticket_title_config_updated_at_trigger ON ticket_title_config;
CREATE TRIGGER ticket_title_config_updated_at_trigger
  BEFORE UPDATE ON ticket_title_config
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS ticket_auto_generation_rules_updated_at_trigger ON ticket_auto_generation_rules;
CREATE TRIGGER ticket_auto_generation_rules_updated_at_trigger
  BEFORE UPDATE ON ticket_auto_generation_rules
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Auto-generate ticket_id
CREATE OR REPLACE FUNCTION generate_ticket_id()
RETURNS TRIGGER AS $$
DECLARE
  year_part TEXT;
  sequence_num INTEGER;
  ticket_prefix TEXT := 'TKT';
BEGIN
  year_part := TO_CHAR(NOW(), 'YYYY');
  
  -- Get next sequence number for this year
  SELECT COALESCE(MAX(CAST(SUBSTRING(ticket_id FROM '\d+$') AS INTEGER)), 0) + 1
  INTO sequence_num
  FROM unified_tickets
  WHERE ticket_id LIKE ticket_prefix || '-' || year_part || '-%';
  
  -- Generate ticket ID: TKT-YYYY-NNNNNN
  NEW.ticket_id := ticket_prefix || '-' || year_part || '-' || LPAD(sequence_num::TEXT, 6, '0');
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS unified_tickets_generate_id_trigger ON unified_tickets;
CREATE TRIGGER unified_tickets_generate_id_trigger
  BEFORE INSERT ON unified_tickets
  FOR EACH ROW
  WHEN (NEW.ticket_id IS NULL OR NEW.ticket_id = '')
  EXECUTE FUNCTION generate_ticket_id();

-- Auto-log activities
CREATE OR REPLACE FUNCTION log_ticket_activity()
RETURNS TRIGGER AS $$
BEGIN
  -- Log status changes
  IF OLD.status IS DISTINCT FROM NEW.status THEN
    INSERT INTO unified_ticket_activities (ticket_id, activity_type, activity_description, actor_type, actor_id, actor_name, old_value, new_value)
    VALUES (
      NEW.id,
      'STATUS_CHANGED',
      'Status changed from ' || OLD.status || ' to ' || NEW.status,
      COALESCE(NEW.raised_by_type, 'SYSTEM'),
      NEW.raised_by_id,
      NEW.raised_by_name,
      jsonb_build_object('status', OLD.status),
      jsonb_build_object('status', NEW.status)
    );
  END IF;
  
  -- Log priority changes
  IF OLD.priority IS DISTINCT FROM NEW.priority THEN
    INSERT INTO unified_ticket_activities (ticket_id, activity_type, activity_description, actor_type, actor_id, actor_name, old_value, new_value)
    VALUES (
      NEW.id,
      'PRIORITY_CHANGED',
      'Priority changed from ' || OLD.priority || ' to ' || NEW.priority,
      COALESCE(NEW.raised_by_type, 'SYSTEM'),
      NEW.raised_by_id,
      NEW.raised_by_name,
      jsonb_build_object('priority', OLD.priority),
      jsonb_build_object('priority', NEW.priority)
    );
  END IF;
  
  -- Log assignment changes
  IF OLD.assigned_to_agent_id IS DISTINCT FROM NEW.assigned_to_agent_id THEN
    INSERT INTO unified_ticket_activities (ticket_id, activity_type, activity_description, actor_type, actor_id, actor_name, old_value, new_value)
    VALUES (
      NEW.id,
      CASE WHEN NEW.assigned_to_agent_id IS NOT NULL THEN 'ASSIGNED' ELSE 'UNASSIGNED' END,
      CASE WHEN NEW.assigned_to_agent_id IS NOT NULL 
        THEN 'Assigned to ' || COALESCE(NEW.assigned_to_agent_name, 'agent')
        ELSE 'Unassigned'
      END,
      'SYSTEM',
      NULL,
      'System',
      jsonb_build_object('assigned_to_agent_id', OLD.assigned_to_agent_id),
      jsonb_build_object('assigned_to_agent_id', NEW.assigned_to_agent_id)
    );
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS unified_tickets_activity_log_trigger ON unified_tickets;
CREATE TRIGGER unified_tickets_activity_log_trigger
  AFTER UPDATE ON unified_tickets
  FOR EACH ROW
  EXECUTE FUNCTION log_ticket_activity();

-- Update first_response_at and first_response_time_minutes
CREATE OR REPLACE FUNCTION update_ticket_response_times()
RETURNS TRIGGER AS $$
BEGIN
  -- Update first response time
  IF NEW.first_response_at IS NULL AND NEW.status != 'OPEN' THEN
    NEW.first_response_at := NOW();
    NEW.first_response_time_minutes := EXTRACT(EPOCH FROM (NEW.first_response_at - NEW.created_at)) / 60;
  END IF;
  
  -- Update last response time
  IF NEW.status IN ('IN_PROGRESS', 'WAITING_FOR_USER', 'WAITING_FOR_MERCHANT', 'WAITING_FOR_RIDER') THEN
    NEW.last_response_at := NOW();
  END IF;
  
  -- Update resolution time
  IF NEW.resolved_at IS NOT NULL AND OLD.resolved_at IS NULL THEN
    NEW.resolution_time_minutes := EXTRACT(EPOCH FROM (NEW.resolved_at - NEW.created_at)) / 60;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS unified_tickets_response_times_trigger ON unified_tickets;
CREATE TRIGGER unified_tickets_response_times_trigger
  BEFORE UPDATE ON unified_tickets
  FOR EACH ROW
  EXECUTE FUNCTION update_ticket_response_times();

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE unified_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE unified_ticket_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE unified_ticket_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_title_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_auto_generation_rules ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE unified_tickets IS 'Unified ticket system supporting all ticket types (order-related and non-order-related) from all sources (customer, rider, merchant, system, email) across all services (food, parcel, ride)';
COMMENT ON TABLE unified_ticket_messages IS 'Conversation thread for tickets - messages from customers, riders, merchants, agents, and system';
COMMENT ON TABLE unified_ticket_activities IS 'Complete audit trail of all ticket activities and changes';
COMMENT ON TABLE ticket_title_config IS 'Configuration table for fixed ticket titles - ensures consistency across the platform';
COMMENT ON TABLE ticket_auto_generation_rules IS 'Rules for automatically generating tickets based on system events';

COMMENT ON COLUMN unified_tickets.ticket_id IS 'Human-readable unique ticket ID (e.g., TKT-2024-001234)';
COMMENT ON COLUMN unified_tickets.ticket_type IS 'Whether ticket is order-related or non-order-related';
COMMENT ON COLUMN unified_tickets.ticket_source IS 'Source of ticket creation (customer, rider, merchant, system, email, etc.)';
COMMENT ON COLUMN unified_tickets.service_type IS 'Service this ticket relates to (food, parcel, ride, general)';
COMMENT ON COLUMN unified_tickets.ticket_title IS 'Fixed title from enum - ensures consistency';
COMMENT ON COLUMN unified_tickets.auto_generated IS 'Whether ticket was auto-generated by system';
COMMENT ON COLUMN unified_tickets.email_thread_id IS 'Email thread ID for grouping related email tickets';
