-- Merchant store documents: one row per store, all document fields (onboarding + verification).
-- Idempotent: use IF NOT EXISTS. For existing DBs with this table, no-op.
-- Ensures document data is saved on step 4 and merged into progress on GET for UI reload.

CREATE TABLE IF NOT EXISTS public.merchant_store_documents (
  id BIGSERIAL NOT NULL,
  store_id BIGINT NOT NULL,
  pan_document_number TEXT NULL,
  pan_document_url TEXT NULL,
  pan_document_name TEXT NULL,
  pan_holder_name TEXT NULL,
  pan_is_verified BOOLEAN NULL DEFAULT false,
  pan_verified_by INTEGER NULL,
  pan_verified_at TIMESTAMP WITH TIME ZONE NULL,
  pan_rejection_reason TEXT NULL,
  pan_issued_date DATE NULL,
  pan_expiry_date DATE NULL,
  pan_is_expired BOOLEAN NULL DEFAULT false,
  pan_document_version INTEGER NULL DEFAULT 1,
  pan_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  pan_uploaded_by INTEGER NULL,
  pan_created_at TIMESTAMP WITH TIME ZONE NULL,
  pan_updated_at TIMESTAMP WITH TIME ZONE NULL,
  gst_document_number TEXT NULL,
  gst_document_url TEXT NULL,
  gst_document_name TEXT NULL,
  gst_is_verified BOOLEAN NULL DEFAULT false,
  gst_verified_by INTEGER NULL,
  gst_verified_at TIMESTAMP WITH TIME ZONE NULL,
  gst_rejection_reason TEXT NULL,
  gst_issued_date DATE NULL,
  gst_expiry_date DATE NULL,
  gst_is_expired BOOLEAN NULL DEFAULT false,
  gst_document_version INTEGER NULL DEFAULT 1,
  gst_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  gst_uploaded_by INTEGER NULL,
  gst_created_at TIMESTAMP WITH TIME ZONE NULL,
  gst_updated_at TIMESTAMP WITH TIME ZONE NULL,
  aadhaar_document_number TEXT NULL,
  aadhaar_document_url TEXT NULL,
  aadhaar_document_name TEXT NULL,
  aadhaar_holder_name TEXT NULL,
  aadhaar_is_verified BOOLEAN NULL DEFAULT false,
  aadhaar_verified_by INTEGER NULL,
  aadhaar_verified_at TIMESTAMP WITH TIME ZONE NULL,
  aadhaar_rejection_reason TEXT NULL,
  aadhaar_issued_date DATE NULL,
  aadhaar_expiry_date DATE NULL,
  aadhaar_is_expired BOOLEAN NULL DEFAULT false,
  aadhaar_document_version INTEGER NULL DEFAULT 1,
  aadhaar_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  aadhaar_uploaded_by INTEGER NULL,
  aadhaar_created_at TIMESTAMP WITH TIME ZONE NULL,
  aadhaar_updated_at TIMESTAMP WITH TIME ZONE NULL,
  fssai_document_number TEXT NULL,
  fssai_document_url TEXT NULL,
  fssai_document_name TEXT NULL,
  fssai_is_verified BOOLEAN NULL DEFAULT false,
  fssai_verified_by INTEGER NULL,
  fssai_verified_at TIMESTAMP WITH TIME ZONE NULL,
  fssai_rejection_reason TEXT NULL,
  fssai_issued_date DATE NULL,
  fssai_expiry_date DATE NULL,
  fssai_is_expired BOOLEAN NULL DEFAULT false,
  fssai_document_version INTEGER NULL DEFAULT 1,
  fssai_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  fssai_uploaded_by INTEGER NULL,
  fssai_created_at TIMESTAMP WITH TIME ZONE NULL,
  fssai_updated_at TIMESTAMP WITH TIME ZONE NULL,
  drug_license_document_number TEXT NULL,
  drug_license_document_url TEXT NULL,
  drug_license_document_name TEXT NULL,
  drug_license_type TEXT NULL,
  drug_license_is_verified BOOLEAN NULL DEFAULT false,
  drug_license_verified_by INTEGER NULL,
  drug_license_verified_at TIMESTAMP WITH TIME ZONE NULL,
  drug_license_rejection_reason TEXT NULL,
  drug_license_issued_date DATE NULL,
  drug_license_expiry_date DATE NULL,
  drug_license_is_expired BOOLEAN NULL DEFAULT false,
  drug_license_document_version INTEGER NULL DEFAULT 1,
  drug_license_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  drug_license_uploaded_by INTEGER NULL,
  drug_license_created_at TIMESTAMP WITH TIME ZONE NULL,
  drug_license_updated_at TIMESTAMP WITH TIME ZONE NULL,
  shop_establishment_document_number TEXT NULL,
  shop_establishment_document_url TEXT NULL,
  shop_establishment_document_name TEXT NULL,
  shop_establishment_is_verified BOOLEAN NULL DEFAULT false,
  shop_establishment_verified_by INTEGER NULL,
  shop_establishment_verified_at TIMESTAMP WITH TIME ZONE NULL,
  shop_establishment_rejection_reason TEXT NULL,
  shop_establishment_issued_date DATE NULL,
  shop_establishment_expiry_date DATE NULL,
  shop_establishment_is_expired BOOLEAN NULL DEFAULT false,
  shop_establishment_document_version INTEGER NULL DEFAULT 1,
  shop_establishment_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  shop_establishment_uploaded_by INTEGER NULL,
  shop_establishment_created_at TIMESTAMP WITH TIME ZONE NULL,
  shop_establishment_updated_at TIMESTAMP WITH TIME ZONE NULL,
  trade_license_document_number TEXT NULL,
  trade_license_document_url TEXT NULL,
  trade_license_document_name TEXT NULL,
  trade_license_is_verified BOOLEAN NULL DEFAULT false,
  trade_license_verified_by INTEGER NULL,
  trade_license_verified_at TIMESTAMP WITH TIME ZONE NULL,
  trade_license_rejection_reason TEXT NULL,
  trade_license_issued_date DATE NULL,
  trade_license_expiry_date DATE NULL,
  trade_license_is_expired BOOLEAN NULL DEFAULT false,
  trade_license_document_version INTEGER NULL DEFAULT 1,
  trade_license_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  trade_license_uploaded_by INTEGER NULL,
  trade_license_created_at TIMESTAMP WITH TIME ZONE NULL,
  trade_license_updated_at TIMESTAMP WITH TIME ZONE NULL,
  udyam_document_number TEXT NULL,
  udyam_document_url TEXT NULL,
  udyam_document_name TEXT NULL,
  udyam_is_verified BOOLEAN NULL DEFAULT false,
  udyam_verified_by INTEGER NULL,
  udyam_verified_at TIMESTAMP WITH TIME ZONE NULL,
  udyam_rejection_reason TEXT NULL,
  udyam_issued_date DATE NULL,
  udyam_expiry_date DATE NULL,
  udyam_is_expired BOOLEAN NULL DEFAULT false,
  udyam_document_version INTEGER NULL DEFAULT 1,
  udyam_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  udyam_uploaded_by INTEGER NULL,
  udyam_created_at TIMESTAMP WITH TIME ZONE NULL,
  udyam_updated_at TIMESTAMP WITH TIME ZONE NULL,
  pharmacist_certificate_document_number TEXT NULL,
  pharmacist_certificate_document_url TEXT NULL,
  pharmacist_certificate_document_name TEXT NULL,
  pharmacist_certificate_is_verified BOOLEAN NULL DEFAULT false,
  pharmacist_certificate_verified_by INTEGER NULL,
  pharmacist_certificate_verified_at TIMESTAMP WITH TIME ZONE NULL,
  pharmacist_certificate_rejection_reason TEXT NULL,
  pharmacist_certificate_issued_date DATE NULL,
  pharmacist_certificate_expiry_date DATE NULL,
  pharmacist_certificate_is_expired BOOLEAN NULL DEFAULT false,
  pharmacist_certificate_document_version INTEGER NULL DEFAULT 1,
  pharmacist_certificate_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  pharmacist_certificate_uploaded_by INTEGER NULL,
  pharmacist_certificate_created_at TIMESTAMP WITH TIME ZONE NULL,
  pharmacist_certificate_updated_at TIMESTAMP WITH TIME ZONE NULL,
  pharmacy_council_registration_document_number TEXT NULL,
  pharmacy_council_registration_document_url TEXT NULL,
  pharmacy_council_registration_document_name TEXT NULL,
  pharmacy_council_registration_type TEXT NULL,
  pharmacy_council_registration_is_verified BOOLEAN NULL DEFAULT false,
  pharmacy_council_registration_verified_by INTEGER NULL,
  pharmacy_council_registration_verified_at TIMESTAMP WITH TIME ZONE NULL,
  pharmacy_council_registration_rejection_reason TEXT NULL,
  pharmacy_council_registration_issued_date DATE NULL,
  pharmacy_council_registration_expiry_date DATE NULL,
  pharmacy_council_registration_is_expired BOOLEAN NULL DEFAULT false,
  pharmacy_council_registration_document_version INTEGER NULL DEFAULT 1,
  pharmacy_council_registration_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  pharmacy_council_registration_uploaded_by INTEGER NULL,
  pharmacy_council_registration_created_at TIMESTAMP WITH TIME ZONE NULL,
  pharmacy_council_registration_updated_at TIMESTAMP WITH TIME ZONE NULL,
  other_document_number TEXT NULL,
  other_document_url TEXT NULL,
  other_document_name TEXT NULL,
  other_document_type TEXT NULL,
  other_is_verified BOOLEAN NULL DEFAULT false,
  other_verified_by INTEGER NULL,
  other_verified_at TIMESTAMP WITH TIME ZONE NULL,
  other_rejection_reason TEXT NULL,
  other_issued_date DATE NULL,
  other_expiry_date DATE NULL,
  other_is_expired BOOLEAN NULL DEFAULT false,
  other_document_version INTEGER NULL DEFAULT 1,
  other_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  other_uploaded_by INTEGER NULL,
  other_created_at TIMESTAMP WITH TIME ZONE NULL,
  other_updated_at TIMESTAMP WITH TIME ZONE NULL,
  bank_proof_document_number TEXT NULL,
  bank_proof_document_url TEXT NULL,
  bank_proof_document_name TEXT NULL,
  bank_proof_is_verified BOOLEAN NULL DEFAULT false,
  bank_proof_verified_by INTEGER NULL,
  bank_proof_verified_at TIMESTAMP WITH TIME ZONE NULL,
  bank_proof_rejection_reason TEXT NULL,
  bank_proof_issued_date DATE NULL,
  bank_proof_expiry_date DATE NULL,
  bank_proof_is_expired BOOLEAN NULL DEFAULT false,
  bank_proof_document_version INTEGER NULL DEFAULT 1,
  bank_proof_document_metadata JSONB NULL DEFAULT '{}'::jsonb,
  bank_proof_uploaded_by INTEGER NULL,
  bank_proof_created_at TIMESTAMP WITH TIME ZONE NULL,
  bank_proof_updated_at TIMESTAMP WITH TIME ZONE NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  CONSTRAINT merchant_store_documents_pkey PRIMARY KEY (id),
  CONSTRAINT merchant_store_documents_store_id_key UNIQUE (store_id),
  CONSTRAINT merchant_store_documents_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.merchant_stores (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS merchant_store_documents_store_id_idx ON public.merchant_store_documents USING btree (store_id);

COMMENT ON TABLE public.merchant_store_documents IS 'One row per store: all onboarding document fields and URLs (R2). Used for step 4 persistence and verification.';
