-- Store status control: manual hold, restriction type, last action display, and full activity log.
-- Ensures: who turned ON/OFF, timestamp, restriction badges; "Until I manually turn it ON" blocks auto-open.

-- 1. merchant_store_availability: block auto-open and restriction type
ALTER TABLE public.merchant_store_availability
  ADD COLUMN IF NOT EXISTS block_auto_open boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS restriction_type text,
  ADD COLUMN IF NOT EXISTS last_toggled_by_name text,
  ADD COLUMN IF NOT EXISTS last_toggled_by_id text;

COMMENT ON COLUMN public.merchant_store_availability.block_auto_open IS 'When true, store must NOT auto-open on schedule; only manual turn ON opens';
COMMENT ON COLUMN public.merchant_store_availability.restriction_type IS 'TEMPORARY | CLOSED_TODAY | MANUAL_HOLD when closed by restriction';
COMMENT ON COLUMN public.merchant_store_availability.last_toggled_by_name IS 'Display name of who last toggled (merchant/admin)';
COMMENT ON COLUMN public.merchant_store_availability.last_toggled_by_id IS 'User/merchant ID for display (e.g. GM1002)';

-- 2. Full store status activity log (for Recent activities, Audit log, accountability)
CREATE TABLE IF NOT EXISTS public.merchant_store_status_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL,
  action text NOT NULL,
  restriction_type text,
  performed_by_id text,
  performed_by_email text,
  performed_by_name text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS merchant_store_status_log_store_id_idx ON public.merchant_store_status_log(store_id);
CREATE INDEX IF NOT EXISTS merchant_store_status_log_created_at_idx ON public.merchant_store_status_log(store_id, created_at DESC);

COMMENT ON TABLE public.merchant_store_status_log IS 'Every store open/close action for accountability and audit';
