-- 0115_seed_cuisine_master.sql
-- Seed cuisine_master with default cuisines from public/data/cuisines.json.
-- Idempotent: uses ON CONFLICT(slug) DO UPDATE.

INSERT INTO public.cuisine_master (slug, name, is_default, is_active, display_order)
VALUES
  ('north-indian', 'North Indian', TRUE, TRUE, 1),
  ('chinese', 'Chinese', TRUE, TRUE, 2),
  ('fast-food', 'Fast Food', TRUE, TRUE, 3),
  ('south-indian', 'South Indian', TRUE, TRUE, 4),
  ('biryani', 'Biryani', TRUE, TRUE, 5),
  ('pizza', 'Pizza', TRUE, TRUE, 6),
  ('bakery', 'Bakery', TRUE, TRUE, 7),
  ('street-food', 'Street Food', TRUE, TRUE, 8),
  ('burger', 'Burger', TRUE, TRUE, 9),
  ('mughlai', 'Mughlai', TRUE, TRUE, 10),
  ('momos', 'Momos', TRUE, TRUE, 11),
  ('sandwich', 'Sandwich', TRUE, TRUE, 12),
  ('mithai', 'Mithai', TRUE, TRUE, 13),
  ('rolls', 'Rolls', TRUE, TRUE, 14),
  ('beverages', 'Beverages', TRUE, TRUE, 15),
  ('desserts', 'Desserts', TRUE, TRUE, 16),
  ('cafe', 'Cafe', TRUE, TRUE, 17),
  ('healthy-food', 'Healthy Food', TRUE, TRUE, 18),
  ('maharashtrian', 'Maharashtrian', TRUE, TRUE, 19),
  ('tea', 'Tea', TRUE, TRUE, 20),
  ('bengali', 'Bengali', TRUE, TRUE, 21),
  ('ice-cream', 'Ice Cream', TRUE, TRUE, 22),
  ('juices', 'Juices', TRUE, TRUE, 23),
  ('shake', 'Shake', TRUE, TRUE, 24),
  ('shawarma', 'Shawarma', TRUE, TRUE, 25),
  ('gujarati', 'Gujarati', TRUE, TRUE, 26),
  ('italian', 'Italian', TRUE, TRUE, 27),
  ('continental', 'Continental', TRUE, TRUE, 28),
  ('lebanese', 'Lebanese', TRUE, TRUE, 29),
  ('salad', 'Salad', TRUE, TRUE, 30),
  ('andhra', 'Andhra', TRUE, TRUE, 31),
  ('waffle', 'Waffle', TRUE, TRUE, 32),
  ('coffee', 'Coffee', TRUE, TRUE, 33),
  ('kebab', 'Kebab', TRUE, TRUE, 34),
  ('arabian', 'Arabian', TRUE, TRUE, 35),
  ('kerala', 'Kerala', TRUE, TRUE, 36),
  ('asian', 'Asian', TRUE, TRUE, 37),
  ('seafood', 'Seafood', TRUE, TRUE, 38),
  ('pasta', 'Pasta', TRUE, TRUE, 39),
  ('bbq', 'BBQ', TRUE, TRUE, 40),
  ('rajasthani', 'Rajasthani', TRUE, TRUE, 41),
  ('wraps', 'Wraps', TRUE, TRUE, 42),
  ('paan', 'Paan', TRUE, TRUE, 43),
  ('hyderabadi', 'Hyderabadi', TRUE, TRUE, 44),
  ('mexican', 'Mexican', TRUE, TRUE, 45),
  ('bihari', 'Bihari', TRUE, TRUE, 46),
  ('goan', 'Goan', TRUE, TRUE, 47),
  ('assamese', 'Assamese', TRUE, TRUE, 48),
  ('american', 'American', TRUE, TRUE, 49),
  ('mandi', 'Mandi', TRUE, TRUE, 50),
  ('chettinad', 'Chettinad', TRUE, TRUE, 51),
  ('mishti', 'Mishti', TRUE, TRUE, 52),
  ('bar-food', 'Bar Food', TRUE, TRUE, 53),
  ('malwani', 'Malwani', TRUE, TRUE, 54),
  ('odia', 'Odia', TRUE, TRUE, 55),
  ('roast-chicken', 'Roast Chicken', TRUE, TRUE, 56),
  ('tamil', 'Tamil', TRUE, TRUE, 57),
  ('japanese', 'Japanese', TRUE, TRUE, 58),
  ('finger-food', 'Finger Food', TRUE, TRUE, 59),
  ('korean', 'Korean', TRUE, TRUE, 60),
  ('north-eastern', 'North Eastern', TRUE, TRUE, 61),
  ('thai', 'Thai', TRUE, TRUE, 62),
  ('kathiyawadi', 'Kathiyawadi', TRUE, TRUE, 63),
  ('bubble-tea', 'Bubble Tea', TRUE, TRUE, 64),
  ('mangalorean', 'Mangalorean', TRUE, TRUE, 65),
  ('burmese', 'Burmese', TRUE, TRUE, 66),
  ('sushi', 'Sushi', TRUE, TRUE, 67),
  ('lucknowi', 'Lucknowi', TRUE, TRUE, 68),
  ('modern-indian', 'Modern Indian', TRUE, TRUE, 69),
  ('tibetan', 'Tibetan', TRUE, TRUE, 70),
  ('afghan', 'Afghan', TRUE, TRUE, 71),
  ('oriental', 'Oriental', TRUE, TRUE, 72),
  ('pancake', 'Pancake', TRUE, TRUE, 73),
  ('kashmiri', 'Kashmiri', TRUE, TRUE, 74),
  ('middle-eastern', 'Middle Eastern', TRUE, TRUE, 75),
  ('grocery', 'Grocery', TRUE, TRUE, 76),
  ('konkan', 'Konkan', TRUE, TRUE, 77),
  ('european', 'European', TRUE, TRUE, 78),
  ('awadhi', 'Awadhi', TRUE, TRUE, 79),
  ('hot-dogs', 'Hot dogs', TRUE, TRUE, 80),
  ('sindhi', 'Sindhi', TRUE, TRUE, 81),
  ('turkish', 'Turkish', TRUE, TRUE, 82),
  ('naga', 'Naga', TRUE, TRUE, 83),
  ('mediterranean', 'Mediterranean', TRUE, TRUE, 84),
  ('nepalese', 'Nepalese', TRUE, TRUE, 85),
  ('cuisine-varies', 'Cuisine Varies', TRUE, TRUE, 86),
  ('saoji', 'Saoji', TRUE, TRUE, 87),
  ('charcoal-chicken', 'Charcoal Chicken', TRUE, TRUE, 88),
  ('steak', 'Steak', TRUE, TRUE, 89),
  ('frozen-yogurt', 'Frozen Yogurt', TRUE, TRUE, 90),
  ('panini', 'Panini', TRUE, TRUE, 91),
  ('parsi', 'Parsi', TRUE, TRUE, 92),
  ('sichuan', 'Sichuan', TRUE, TRUE, 93),
  ('iranian', 'Iranian', TRUE, TRUE, 94),
  ('grilled-chicken', 'Grilled Chicken', TRUE, TRUE, 95),
  ('french', 'French', TRUE, TRUE, 96),
  ('raw-meats', 'Raw Meats', TRUE, TRUE, 97),
  ('drinks-only', 'Drinks Only', TRUE, TRUE, 98),
  ('vietnamese', 'Vietnamese', TRUE, TRUE, 99),
  ('liquor', 'Liquor', TRUE, TRUE, 100),
  ('greek', 'Greek', TRUE, TRUE, 101),
  ('himachali', 'Himachali', TRUE, TRUE, 102),
  ('bohri', 'Bohri', TRUE, TRUE, 103),
  ('garhwali', 'Garhwali', TRUE, TRUE, 104),
  ('cantonese', 'Cantonese', TRUE, TRUE, 105),
  ('malaysian', 'Malaysian', TRUE, TRUE, 106),
  ('belgian', 'Belgian', TRUE, TRUE, 107),
  ('british', 'British', TRUE, TRUE, 108),
  ('african', 'African', TRUE, TRUE, 109),
  ('spanish', 'Spanish', TRUE, TRUE, 110),
  ('manipuri', 'Manipuri', TRUE, TRUE, 111),
  ('egyptian', 'Egyptian', TRUE, TRUE, 112),
  ('sri-lankan', 'Sri Lankan', TRUE, TRUE, 113),
  ('relief-fund', 'Relief fund', TRUE, TRUE, 114),
  ('bangladeshi', 'Bangladeshi', TRUE, TRUE, 115),
  ('indonesian', 'Indonesian', TRUE, TRUE, 116),
  ('tex-mex', 'Tex-Mex', TRUE, TRUE, 117),
  ('irish', 'Irish', TRUE, TRUE, 118),
  ('singaporean', 'Singaporean', TRUE, TRUE, 119),
  ('south-american', 'South American', TRUE, TRUE, 120),
  ('mongolian', 'Mongolian', TRUE, TRUE, 121),
  ('german', 'German', TRUE, TRUE, 122),
  ('russian', 'Russian', TRUE, TRUE, 123),
  ('brazilian', 'Brazilian', TRUE, TRUE, 124),
  ('pakistani', 'Pakistani', TRUE, TRUE, 125),
  ('australian', 'Australian', TRUE, TRUE, 126),
  ('moroccan', 'Moroccan', TRUE, TRUE, 127),
  ('filipino', 'Filipino', TRUE, TRUE, 128),
  ('hot-pot', 'Hot Pot', TRUE, TRUE, 129),
  ('retail-products', 'Retail Products', TRUE, TRUE, 130),
  ('mizo', 'Mizo', TRUE, TRUE, 131),
  ('portuguese', 'Portuguese', TRUE, TRUE, 132),
  ('indian', 'Indian', TRUE, TRUE, 133),
  ('tripuri', 'Tripuri', TRUE, TRUE, 134),
  ('delight-goodies', 'Delight Goodies', TRUE, TRUE, 135),
  ('meghalayan', 'Meghalayan', TRUE, TRUE, 136),
  ('sikkimese', 'Sikkimese', TRUE, TRUE, 137),
  ('armenian', 'Armenian', TRUE, TRUE, 138),
  ('afghani', 'Afghani', TRUE, TRUE, 139)
ON CONFLICT (slug) DO UPDATE
SET
  name = EXCLUDED.name,
  is_default = TRUE,
  is_active = TRUE;

